### ISSUE TITLE
Improved speed of opening group folders

### ISSUE THREAD

**Issue by laurent734** [trix7777/m2strm#10]
hello, could you add an option in the config file for . strm be stored in a folder ...(only for VOD MOVIES ).
This makes it much easier to open a group folder that is shared on a Samba network or stored on a cloud for remote access .( much faster ).
I tried to do it with tinymediamanager but the problem is that the files are overwritten every time the script is executed.
Thank you for your work.

**Comment by trix7777** [comment]
You have to be more specific, give an example for what you want. I am on a samba network and neither Kodi nor Jellyfin have any problems with that.

**Comment by laurent734** [comment]
I made a video demonstration of the problem.
test1- the .strm are stored in folders
test2 - the .strm are not stored in folders
The action folder contains 1200 movies.
Here is the download link for the test video.
https://saphir.ddns.net/s/x7bdFQ6DZyDnica

thank you

**Comment by trix7777** [comment]
File not found
Please use Youtube.

**Comment by laurent734** [comment]
https://drive.google.com/file/d/13i6T_AvFVziBuMWMCYWO7vgMdeD6boK2/view?usp=sharing
ok.
here is a google drive link .. i don’t have a youtube account

**Comment by trix7777** [comment]
I don't really get what you want, do you want each movie to end up in its own subfolder named the same as the strm-file? May I suggest you try using a real media player instead like Kodi? What setup do you have working that bad? Taking forever to go to a subdir, feels like Windows-XP-with-Windows -Media-Player-slow.

**Comment by laurent734** [comment]
Hello,
can i use some of your code?
I would like to use the part of //removes illegal file name characters (regex) which will be used in a kodi 19 plugin...
thank you

**Comment by trix7777** [comment]
> Hello, can i use some of your code? I would like to use the part of //removes illegal file name characters (regex) which will be used in a kodi 19 plugin... thank you

Sorry, I must have missed your question, and now, almost a year later; you can use it as long as it complies with the [GPL-3.0 license](https://github.com/trix7777/m2strm/blob/main/LICENSE)
