### ISSUE TITLE
404 not found without any useful information to resolve

### ISSUE THREAD

**Issue by lt-columbo** [trix7777/m2strm#20]
I appreciate your effort here but I'm having trouble on Ubuntu 22.04

I'm using iptv-editor.com and the stream feeds don't match any examples.

I've tried the url alone (https://host/xyxuser/123pass) w/o user or password values (because the iptv urls don't have username and password just /username/password), get a 404. Using same url pasted into wget it's 100% fine.

I've tried all of the alternatives using the xstream feed options (which also don't match because they have a '&type=m3u_plus' tacked on the end. I stuck that on the end of the password and got a stack trace.

The only information I get back from m2strm is '404 not found'. A nice feature would be to provide the url you are trying so we're not walking around in the dark? Perhap obfuscate the user/pass values some, but at least show the built url

I ventured into the error.log and get same info:
ERROR: The remote server returned an error: (404) Not Found.

**Comment by trix7777** [comment]
Sorry for a very late answer, but with that url you give as an example  (https://host/xyxuser/123pass) this app will not currently work for you, it needs to be like this to work:
`http://ip.tv:8080/get.php?username=ABCDEFGHIJ&password=0123456789&type=m3u_plus&output=ts`
or without the port (will be port 80 if not given)
`http://ip.tv/get.php?username=ABCDEFGHIJ&password=0123456789&type=m3u_plus&output=ts`
were ABCDEFGHIJ is your username and 0123456789 your password.
This is exactly what this app sends to the server.

**Comment by trix7777** [comment]
Not a bug.
