### ISSUE TITLE
 ERROR: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by AshCooperUK** [trix7777/m2strm#22]
ERROR: Index was outside the bounds of the array.
I have started to get this error. Been using it for a few years, only recently. I was hoping for a version of the older releases so I can confirm if it an isolated issue with the latest or not. 

Thanks.

**Comment by trix7777** [comment]
I think this is caused by a faulty m3u8, I have some of those in my error.log too. You should download the m3u8 manually and check it when this happens.

**Comment by AshCooperUK** [comment]
![image](https://github.com/trix7777/m2strm/assets/102906756/db7ab97a-fbf1-4749-8221-64c9ce2a542b)

Yup! thats the issue! thanks. im speaking with my provider for a fix.
